apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: petclinic      
        name: petclinic
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic

spec:
  ports:
    - nodePort: 30163
      port: 8080
      protocol: TCP
      targetPort: 8080
  

  type: LoadBalancer
  selector:
       app: petclinic
  type: NodePort 